FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/runtime:7.0.13-alpine3.18-arm64v8 AS base
WORKDIR /app

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0-alpine-arm64v8 AS build
WORKDIR /src
COPY ["Promul.csproj", "./"]
RUN dotnet restore "Promul.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "Promul.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Promul.csproj" -c Release -o /app/publish -r linux-arm64 --self-contained false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 4098
ENTRYPOINT ["dotnet", "Promul.dll"]
